set(DEPS_DIR ../DeathMatchDepsWin)
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(DEPS_BINDIR_PREFIX ${DEPS_DIR}/bin/x64)
else()
  set(DEPS_BINDIR_PREFIX ${DEPS_DIR}/bin/Win32)
endif()

set(DEPS_DEBUG_DLLS ${DEPS_BINDIR_PREFIX}/Debug/SDL2.dll)
set(DEPS_RELEASE_DLLS ${DEPS_BINDIR_PREFIX}/Release/SDL2.dll)

file(COPY
  ${DEPS_DEBUG_DLLS}
  DESTINATION ${CMAKE_BINARY_DIR}/Debug
)

file(COPY
  ${DEPS_RELEASE_DLLS}
  DESTINATION ${CMAKE_BINARY_DIR}/Release
)

file(COPY
  ${DEPS_RELEASE_DLLS}
  DESTINATION ${CMAKE_BINARY_DIR}/MinSizeRel
)

file(COPY
  ${DEPS_RELEASE_DLLS}
  DESTINATION ${CMAKE_BINARY_DIR}/RelWithDebInfo
)
